// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi4XrQ5zTc86yWXnrib0fr7MBfLBsIVNs',
    appId: '1:764788635625:web:37c3d18021c80579e0fd78',
    messagingSenderId: '764788635625',
    projectId: 'health-connect-17c6b',
    authDomain: 'health-connect-17c6b.firebaseapp.com',
    storageBucket: 'health-connect-17c6b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlFCCrmZ8_wtx9-TGbD9mvg2d43TAN5kg',
    // 1:764788635625:android:05a04063c1dcd7f4e0fd78
    appId: '1:764788635625:android:05a04063c1dcd7f4e0fd78',
    messagingSenderId: '764788635625',
    projectId: 'health-connect-17c6b',
    storageBucket: 'health-connect-17c6b.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHnxBhU0xNChysmidmJ-rMM46dfe8h3TA',
    appId: '1:764788635625:ios:46a2c0dfdf1d2eb1e0fd78',
    messagingSenderId: '764788635625',
    projectId: 'health-connect-17c6b',
    storageBucket: 'health-connect-17c6b.firebasestorage.app',
    androidClientId: '764788635625-8c9sg9efr6u0o0aepjrgi97m601nn0ai.apps.googleusercontent.com',
    iosClientId: '764788635625-st6uh6ni68dr9ukma7bv645pv5g8a4uh.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthconnect',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHnxBhU0xNChysmidmJ-rMM46dfe8h3TA',
    appId: '1:764788635625:ios:46a2c0dfdf1d2eb1e0fd78',
    messagingSenderId: '764788635625',
    projectId: 'health-connect-17c6b',
    storageBucket: 'health-connect-17c6b.firebasestorage.app',
    androidClientId: '764788635625-8c9sg9efr6u0o0aepjrgi97m601nn0ai.apps.googleusercontent.com',
    iosClientId: '764788635625-st6uh6ni68dr9ukma7bv645pv5g8a4uh.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi4XrQ5zTc86yWXnrib0fr7MBfLBsIVNs',
    appId: '1:764788635625:web:e16d9dccff2800d9e0fd78',
    messagingSenderId: '764788635625',
    projectId: 'health-connect-17c6b',
    authDomain: 'health-connect-17c6b.firebaseapp.com',
    storageBucket: 'health-connect-17c6b.firebasestorage.app',
  );
}
