class Medicinelist {

  static final List<String> medicineList = [

    // Fever & Pain
    "Paracetamol",
    "Crocin",
    "Dolo 650",
    "Calpol",
    "Aspirin",
    "Disprin",
    "Ibuprofen",
    "Brufen",
    "Combiflam",
    "Aceclofenac",
    "Diclofenac",
    "Ketorol",
    "Tramadol",
    "Ultracet",
    "Naproxen",
    "Meftal Forte",
    "Meftal Spas",
    "Cyclopam",

    // Antibiotics
    "Azithromycin",
    "Amoxicillin",
    "Augmentin",
    "Ciprofloxacin",
    "Ofloxacin",
    "Norflox TZ",
    "Taxim",
    "Cefixime",
    "Doxycycline",
    "Levofloxacin",
    "Metronidazole",
    "Clavam",
    "Zifi",
    "Azee",
    "Moxikind",
    "Monocef",

    // Diabetes
    "Metformin",
    "Glycomet",
    "Glimipride",
    "Amaryl",
    "Janumet",
    "Insulin",
    "Human Mixtard",
    "Insulin Glargine",
    "Insulin Regular",
    "Voglibose",

    // BP & Heart
    "Amlodipine",
    "Telmisartan",
    "Telma",
    "Losartan",
    "Atenolol",
    "Nebicard",
    "Nicardia",
    "Eritel",
    "Clopidogrel",
    "Ecosprin",
    "Warfarin",
    "Atorvastatin",
    "Rosuvastatin",
    "Lasix",
    "Torsemide",

    // Acidity & Digestion
    "Pantoprazole",
    "Pan D",
    "Omeprazole",
    "Rabeprazole",
    "Esomeprazole",
    "Ranitidine",
    "Digene",
    "Gelusil",
    "Eno",
    "Mucaine Gel",
    "Domperidone",
    "Ondansetron",
    "Pudin Hara",
    "Looz",
    "Duphalac",
    "Dulcolax",

    // Allergy & Cold
    "Cetirizine",
    "Levocetirizine",
    "Allegra",
    "Avil",
    "Piriton",
    "Sinarest",
    "Montek LC",
    "Montair",
    "Benadryl",
    "Ascoril",
    "Alex Syrup",
    "TusQ",
    "Grilinctus",
    "Dabur Honitus",
    "Vicks VapoRub",
    "Strepsils",

    // Asthma & Breathing
    "Asthalin",
    "Budecort",
    "Deriphyllin",
    "Foracort",
    "Duolin",
    "Levolin",
    "Seroflo",
    "Aerocort",

    // Vitamins & Supplements
    "Vitamin D3",
    "Calcium Tablet",
    "Shelcal",
    "Iron Tablet",
    "Zincovit",
    "Neurobion Forte",
    "Revital",
    "Supradyn",
    "Becosules",
    "A to Z Multivitamin",
    "Evion 400",
    "Limcee",
    "Gemcal",
    "Feronia",
    "Folvite",
    "Eldervit",

    // Thyroid
    "Thyroxine",
    "Thyronorm",

    // Skin & Creams
    "Boroline",
    "Betadine",
    "Soframycin",
    "Calamine Lotion",
    "Candid Cream",
    "Clotrimazole",
    "Panderm",
    "Silverex",
    "Betnovate",
    "Quadriderm",

    // First Aid
    "Dettol",
    "Savlon",
    "Band Aid",
    "ORS",
    "Electral",

    // Joint Pain & Muscle Relief
    "Volini",
    "Moov",
    "Iodex",
    "Omnigel",

    // Eye & Ear
    "Refresh Tears",
    "Lubrex Eye Drops",
    "Ciplox Eye Drops",
    "Otrivin",
    "Nasivion",

    // Common Indian Medicines
    "D Cold Total",
    "Saridon",
    "Anacin",
    "Flagyl",
    "Rablet",
    "Aciloc",
    "Sporlac",
    "Vizylac",
    "Bifilac",
    "Eldoper",
    "Taxim O",
    "Calciquick",
    "Mucinac",
    "Chericof",
    "Corex",
    "Tuspel",
    "Razo",
    "Nise",
    "Nimulid",
    "Voveran",
    "PCM",
    "Febrex Plus",
    "Himalaya Liv 52",
    "Septilin",
    "Honitus",
    "Koflet",
    "Chyawanprash",
  ];

}